using CommunityToolkit.Mvvm.ComponentModel;

namespace FlagGuesser.Flags;

public partial class FlagsView : ObservableObject
{
    [ObservableProperty]
    public static List<Flag> flags;

    public FlagsView()
    {
        LoadFlags();
    }

    void LoadFlags()
    {
        Flags = new()
        {
            new Flag
                (country: "China",
                flag: "china.png",
                difficulty: 1),
            new Flag
                (country: "India",
                flag: "india.png",
                difficulty: 1),
            new Flag
                (country: "United States",
                flag: "united_states.png",
                difficulty: 1),
            new Flag
                (country: "Indonesia",
                flag: "indonesia.png",
                difficulty: 2),
            new Flag
                (country: "Pakistan",
                flag: "pakistan.png",
                difficulty: 2),
            new Flag
                (country: "Nigeria",
                flag: "nigeria.png",
                difficulty: 2),
            new Flag
                (country: "Brazil",
                flag: "brazil.png",
                difficulty: 1),
            new Flag
                (country: "Bangladesh",
                flag: "bangladesh.png",
                difficulty: 3),
            new Flag
                (country: "Russia",
                flag: "russia.png",
                difficulty: 1),
            new Flag
                (country: "Mexico",
                flag: "mexico.png",
                difficulty: 1),
            new Flag
                (country: "Japan",
                flag: "japan.png",
                difficulty: 1),
            new Flag
                (country: "Philippines",
                flag: "philippines.png",
                difficulty: 2),
            new Flag
                (country: "Ethiopia",
                flag: "ethiopia.png",
                difficulty: 3),
            new Flag
                (country: "Egypt",
                flag: "egypt.png",
                difficulty: 1),
            new Flag
                (country: "Vietnam",
                flag: "vietnam.png",
                difficulty: 2),
            new Flag
                (country: "Democratic Republic of the Congo",
                flag: "democratic_republic_of_the_congo.png",
                difficulty: 3),
            new Flag
                (country: "Iran",
                flag: "iran.png",
                difficulty: 2),
            new Flag
                (country: "Turkey",
                flag: "turkey.png",
                difficulty: 1),
            new Flag
                (country: "Germany",
                flag: "germany.png",
                difficulty: 1),
            new Flag
                (country: "Thailand",
                flag: "thailand.png",
                difficulty: 2),
            new Flag
                (country: "France",
                flag: "france.png",
                difficulty: 1),
            new Flag
                (country: "United Kingdom",
                flag: "united_kingdom.png",
                difficulty: 1),
            new Flag
                (country: "Tanzania",
                flag: "tanzania.png",
                difficulty: 3),
            new Flag
                (country: "South Africa",
                flag: "south_africa.png",
                difficulty: 2),
            new Flag
                (country: "Italy",
                flag: "italy.png",
                difficulty: 1),
            new Flag
                (country: "Myanmar",
                flag: "myanmar.png",
                difficulty: 3),
            new Flag
                (country: "Colombia",
                flag: "colombia.png",
                difficulty: 1),
            new Flag
                (country: "Kenya",
                flag: "kenya.png",
                difficulty: 3),
            new Flag
                (country: "South Korea",
                flag: "south_korea.png",
                difficulty: 1),
            new Flag
                (country: "Spain",
                flag: "spain.png",
                difficulty: 1),
            new Flag
                (country: "Argentina",
                flag: "argentina.png",
                difficulty: 1),
            new Flag
                (country: "Algeria",
                flag: "algeria.png",
                difficulty: 2),
            new Flag
                (country: "Iraq",
                flag: "iraq.png",
                difficulty: 2),
            new Flag
                (country: "Uganda",
                flag: "uganda.png",
                difficulty: 3),
            new Flag
                (country: "Sudan",
                flag: "sudan.png",
                difficulty: 3),
            new Flag
                (country: "Ukraine",
                flag: "ukraine.png",
                difficulty: 1),
            new Flag
                (country: "Canada",
                flag: "canada.png",
                difficulty: 1),
            new Flag
                (country: "Poland",
                flag: "poland.png",
                difficulty: 1),
            new Flag
                (country: "Morocco",
                flag: "morocco.png",
                difficulty: 2),
            new Flag
                (country: "Uzbekistan",
                flag: "uzbekistan.png",
                difficulty: 3),
            new Flag
                (country: "Afghanistan",
                flag: "afghanistan.png",
                difficulty: 3),
            new Flag
                (country: "Peru",
                flag: "peru.png",
                difficulty: 2),
            new Flag
                (country: "Angola",
                flag: "angola.png",
                difficulty: 3),
            new Flag
                (country: "Malaysia",
                flag: "malaysia.png",
                difficulty: 3),
            new Flag
                (country: "Mozambique",
                flag: "mozambique.png",
                difficulty: 2),
            new Flag
                (country: "Saudi Arabia",
                flag: "saudi_arabia.png",
                difficulty: 1),
            new Flag
                (country: "Yemen",
                flag: "yemen.png",
                difficulty: 3),
            new Flag
                (country: "Ghana",
                flag: "ghana.png",
                difficulty: 2),
            new Flag
                (country: "Ivory Coast",
                flag: "ivory_coast.png",
                difficulty: 2),
            new Flag
                (country: "Nepal",
                flag: "nepal.png",
                difficulty: 1),
            new Flag
                (country: "Venezuela",
                flag: "venezuela.png",
                difficulty: 3),
            new Flag
                (country: "Madagascar",
                flag: "madagascar.png",
                difficulty: 3),
            new Flag
                (country: "Australia",
                flag: "australia.png",
                difficulty: 1),
            new Flag
                (country: "North Korea",
                flag: "north_korea.png",
                difficulty: 2),
            new Flag
                (country: "Cameroon",
                flag: "cameroon.png",
                difficulty: 2),
            new Flag
                (country: "Niger",
                flag: "niger.png",
                difficulty: 3),
            new Flag
                (country: "Mali",
                flag: "mali.png",
                difficulty: 3),
            new Flag
                (country: "Syria",
                flag: "syria.png",
                difficulty: 2),
            new Flag
                (country: "Burkina Faso",
                flag: "burkina_faso.png",
                difficulty: 3),
            new Flag
                (country: "Sri Lanka",
                flag: "sri_lanka.png",
                difficulty: 3),
            new Flag
                (country: "Malawi",
                flag: "malawi.png",
                difficulty: 3),
            new Flag
                (country: "Chile",
                flag: "chile.png",
                difficulty: 1),
            new Flag
                (country: "Kazakhstan",
                flag: "kazakhstan.png",
                difficulty: 2),
            new Flag
                (country: "Zambia",
                flag: "zambia.png",
                difficulty: 3),
            new Flag
                (country: "Romania",
                flag: "romania.png",
                difficulty: 1),
            new Flag
                (country: "Ecuador",
                flag: "ecuador.png",
                difficulty: 2),
            new Flag
                (country: "Netherlands",
                flag: "netherlands.png",
                difficulty: 1),
            new Flag
                (country: "Somalia",
                flag: "somalia.png",
                difficulty: 3),
            new Flag
                (country: "Senegal",
                flag: "senegal.png",
                difficulty: 3),
            new Flag
                (country: "Guatemala",
                flag: "guatemala.png",
                difficulty: 3),
            new Flag
                (country: "Chad",
                flag: "chad.png",
                difficulty: 2),
            new Flag
                (country: "Cambodia",
                flag: "cambodia.png",
                difficulty: 3),
            new Flag
                (country: "Zimbabwe",
                flag: "zimbabwe.png",
                difficulty: 2),
            new Flag
                (country: "Guinea",
                flag: "guinea.png",
                difficulty: 3),
            new Flag
                (country: "South Sudan",
                flag: "south_sudan.png",
                difficulty: 3),
            new Flag
                (country: "Rwanda",
                flag: "rwanda.png",
                difficulty: 3),
            new Flag
                (country: "Burundi",
                flag: "burundi.png",
                difficulty: 3),
            new Flag
                (country: "Benin",
                flag: "benin.png",
                difficulty: 3),
            new Flag
                (country: "Bolivia",
                flag: "bolivia.png",
                difficulty: 3),
            new Flag
                (country: "Tunisia",
                flag: "tunisia.png",
                difficulty: 2),
            new Flag
                (country: "Belgium",
                flag: "belgium.png",
                difficulty: 1),
            new Flag
                (country: "Haiti",
                flag: "haiti.png",
                difficulty: 3),
            new Flag
                (country: "Jordan",
                flag: "jordan.png",
                difficulty: 3),
            new Flag
                (country: "Cuba",
                flag: "cuba.png",
                difficulty: 2),
            new Flag
                (country: "Czech Republic",
                flag: "czech_republic.png",
                difficulty: 2),
            new Flag
                (country: "Sweden",
                flag: "sweden.png",
                difficulty: 1),
            new Flag
                (country: "Dominican Republic",
                flag: "dominican_republic.png",
                difficulty: 2),
            new Flag
                (country: "Greece",
                flag: "greece.png",
                difficulty: 1),
            new Flag
                (country: "Portugal",
                flag: "portugal.png",
                difficulty: 1),
            new Flag
                (country: "Azerbaijan",
                flag: "azerbaijan.png",
                difficulty: 3),
            new Flag
                (country: "Israel",
                flag: "israel.png",
                difficulty: 1),
            new Flag
                (country: "Hungary",
                flag: "hungary.png",
                difficulty: 1),
            new Flag
                (country: "Honduras",
                flag: "honduras.png",
                difficulty: 3),
            new Flag
                (country: "Tajikistan",
                flag: "tajikistan.png",
                difficulty: 3),
            new Flag
                (country: "United Arab Emirates",
                flag: "united_arab_emirates.png",
                difficulty: 1),
            new Flag
                (country: "Belarus",
                flag: "belarus.png",
                difficulty: 2),
            new Flag
                (country: "Papua New Guinea",
                flag: "papua_new_guinea.png",
                difficulty: 3),
            new Flag
                (country: "Austria",
                flag: "austria.png",
                difficulty: 1),
            new Flag
                (country: "Switzerland",
                flag: "switzerland.png",
                difficulty: 1),
            new Flag
                (country: "Sierra Leone",
                flag: "sierra_leone.png",
                difficulty: 3),
            new Flag
                (country: "Togo",
                flag: "togo.png",
                difficulty: 3),
            new Flag
                (country: "Paraguay",
                flag: "paraguay.png",
                difficulty: 3),
            new Flag
                (country: "Laos",
                flag: "laos.png",
                difficulty: 3),
            new Flag
                (country: "Kyrgyzstan",
                flag: "kyrgyzstan.png",
                difficulty: 3),
            new Flag
                (country: "Libya",
                flag: "libya.png",
                difficulty: 3),
            new Flag
                (country: "El Salvador",
                flag: "el_salvador.png",
                difficulty: 2),
            new Flag
                (country: "Serbia",
                flag: "serbia.png",
                difficulty: 1),
            new Flag
                (country: "Nicaragua",
                flag: "nicaragua.png",
                difficulty: 3),
            new Flag
                (country: "Turkmenistan",
                flag: "turkmenistan.png",
                difficulty: 3),
            new Flag
                (country: "Bulgaria",
                flag: "bulgaria.png",
                difficulty: 2),
            new Flag
                (country: "Republic of the Congo",
                flag: "republic_of_the_congo.png",
                difficulty: 3),
            new Flag
                (country: "Denmark",
                flag: "denmark.png",
                difficulty: 1),
            new Flag
                (country: "Central African Republic",
                flag: "central_african_republic.png",
                difficulty: 2),
            new Flag
                (country: "Finland",
                flag: "finland.png",
                difficulty: 1),
            new Flag
                (country: "Norway",
                flag: "norway.png",
                difficulty: 1),
            new Flag
                (country: "Lebanon",
                flag: "lebanon.png",
                difficulty: 3),
            new Flag
                (country: "State of Palestine",
                flag: "state_of_palestine.png",
                difficulty: 3),
            new Flag
                (country: "Singapore",
                flag: "singapore.png",
                difficulty: 3),
            new Flag
                (country: "Slovakia",
                flag: "slovakia.png",
                difficulty: 2),
            new Flag
                (country: "Costa Rica",
                flag: "costa_rica.png",
                difficulty: 2),
            new Flag
                (country: "New Zealand",
                flag: "new_zealand.png",
                difficulty: 2),
            new Flag
                (country: "Ireland",
                flag: "ireland.png",
                difficulty: 3),
            new Flag
                (country: "Oman",
                flag: "oman.png",
                difficulty: 3),
            new Flag
                (country: "Kuwait",
                flag: "kuwait.png",
                difficulty: 3),
            new Flag
                (country: "Liberia",
                flag: "liberia.png",
                difficulty: 3),
            new Flag
                (country: "Mauritania",
                flag: "mauritania.png",
                difficulty: 3),
            new Flag
                (country: "Panama",
                flag: "panama.png",
                difficulty: 3),
            new Flag
                (country: "Croatia",
                flag: "croatia.png",
                difficulty: 1),
            new Flag
                (country: "Eritrea",
                flag: "eritrea.png",
                difficulty: 3),
            new Flag
                (country: "Georgia",
                flag: "georgia.png",
                difficulty: 3),
            new Flag
                (country: "Uruguay",
                flag: "uruguay.png",
                difficulty: 2),
            new Flag
                (country: "Mongolia",
                flag: "mongolia.png",
                difficulty: 3),
            new Flag
                (country: "Bosnia and Herzegovina",
                flag: "bosnia_and_herzegovina.png",
                difficulty: 3),
            new Flag
                (country: "Qatar",
                flag: "qatar.png",
                difficulty: 3),
            new Flag
                (country: "Armenia",
                flag: "armenia.png",
                difficulty: 3),
            new Flag
                (country: "Lithuania",
                flag: "lithuania.png",
                difficulty: 2),
            new Flag
                (country: "Jamaica",
                flag: "jamaica.png",
                difficulty: 2),
            new Flag
                (country: "Albania",
                flag: "albania.png",
                difficulty: 2),
            new Flag
                (country: "Moldova",
                flag: "moldova.png",
                difficulty: 2),
            new Flag
                (country: "Namibia",
                flag: "namibia.png",
                difficulty: 3),
            new Flag
                (country: "Gambia",
                flag: "gambia.png",
                difficulty: 3),
            new Flag
                (country: "Botswana",
                flag: "botswana.png",
                difficulty: 3),
            new Flag
                (country: "Lesotho",
                flag: "lesotho.png",
                difficulty: 3),
            new Flag
                (country: "Gabon",
                flag: "gabon.png",
                difficulty: 3),
            new Flag
                (country: "Slovenia",
                flag: "slovenia.png",
                difficulty: 1),
            new Flag
                (country: "Latvia",
                flag: "latvia.png",
                difficulty: 2),
            new Flag
                (country: "North Macedonia",
                flag: "north_macedonia.png",
                difficulty: 3),
            new Flag
                (country: "Guinea-Bissau",
                flag: "guinea_bissau.png",
                difficulty: 3),
            new Flag
                (country: "Equatorial Guinea",
                flag: "equatorial_guinea.png",
                difficulty: 3),
            new Flag
                (country: "Bahrain",
                flag: "bahrain.png",
                difficulty: 3),
            new Flag
                (country: "Estonia",
                flag: "estonia.png",
                difficulty: 2),
            new Flag
                (country: "Trinidad and Tobago",
                flag: "trinidad_and_tobago.png",
                difficulty: 3),
            new Flag
                (country: "East Timor",
                flag: "east_timor.png",
                difficulty: 3),
            new Flag
                (country: "Mauritius",
                flag: "mauritius.png",
                difficulty: 3),
            new Flag
                (country: "Eswatini",
                flag: "eswatini.png",
                difficulty: 3),
            new Flag
                (country: "Djibouti",
                flag: "djibouti.png",
                difficulty: 3),
            new Flag
                (country: "Cyprus",
                flag: "cyprus.png",
                difficulty: 2),
            new Flag
                (country: "Fiji",
                flag: "fiji.png",
                difficulty: 3),
            new Flag
                (country: "Bhutan",
                flag: "bhutan.png",
                difficulty: 3),
            new Flag
                (country: "Comoros",
                flag: "comoros.png",
                difficulty: 3),
            new Flag
                (country: "Guyana",
                flag: "guyana.png",
                difficulty: 3),
            new Flag
                (country: "Solomon Islands",
                flag: "solomon_islands.png",
                difficulty: 3),
            new Flag
                (country: "Luxembourg",
                flag: "luxembourg.png",
                difficulty: 2),
            new Flag
                (country: "Montenegro",
                flag: "montenegro.png",
                difficulty: 3),
            new Flag
                (country: "Suriname",
                flag: "suriname.png",
                difficulty: 3),
            new Flag
                (country: "Cape Verde",
                flag: "cape_verde.png",
                difficulty: 3),
            new Flag
                (country: "Malta",
                flag: "malta.png",
                difficulty: 2),
            new Flag
                (country: "Belize",
                flag: "belize.png",
                difficulty: 3),
            new Flag
                (country: "Brunei",
                flag: "brunei.png",
                difficulty: 3),
            new Flag
                (country: "Maldives",
                flag: "maldives.png",
                difficulty: 2),
            new Flag
                (country: "Bahamas",
                flag: "bahamas.png",
                difficulty: 3),
            new Flag
                (country: "Iceland",
                flag: "iceland.png",
                difficulty: 2),
            new Flag
                (country: "Vanuatu",
                flag: "vanuatu.png",
                difficulty: 3),
            new Flag
                (country: "Barbados",
                flag: "barbados.png",
                difficulty: 3),
            new Flag
                (country: "São Tomé and Príncipe",
                flag: "sao_tome_and_principe.png",
                difficulty: 3),
            new Flag
                (country: "Samoa",
                flag: "samoa.png",
                difficulty: 3),
            new Flag
                (country: "Saint Lucia",
                flag: "saint_lucia.png",
                difficulty: 3),
            new Flag
                (country: "Kiribati",
                flag: "kiribati.png",
                difficulty: 3),
            new Flag
                (country: "Grenada",
                flag: "grenada.png",
                difficulty: 2),
            new Flag
                (country: "Saint Vincent and the Grenadines",
                flag: "saint_vincent_and_the_grenadines.png",
                difficulty: 3),
            new Flag
                (country: "Federated States of Micronesia",
                flag: "federated_states_of_micronesia.png",
                difficulty: 3),
            new Flag
                (country: "Antigua and Barbuda",
                flag: "antigua_and_barbuda.png",
                difficulty: 3),
            new Flag
                (country: "Seychelles",
                flag: "seychelles.png",
                difficulty: 3),
            new Flag
                (country: "Tonga",
                flag: "tonga.png",
                difficulty: 3),
            new Flag
                (country: "Andorra",
                flag: "andorra.png",
                difficulty: 3),
            new Flag
                (country: "Dominica",
                flag: "dominica.png",
                difficulty: 3),
            new Flag
                (country: "Saint Kitts and Nevis",
                flag: "saint_kitts_and_nevis.png",
                difficulty: 3),
            new Flag
                (country: "Liechtenstein",
                flag: "liechtenstein.png",
                difficulty: 2),
            new Flag
                (country: "Marshall Islands",
                flag: "marshall_islands.png",
                difficulty: 3),
            new Flag
                (country: "Monaco",
                flag: "monaco.png",
                difficulty: 2),
            new Flag
                (country: "San Marino",
                flag: "san_marino.png",
                difficulty: 2),
            new Flag
                (country: "Palau",
                flag: "palau.png",
                difficulty: 3),
            new Flag
                (country: "Nauru",
                flag: "nauru.png",
                difficulty: 3),
            new Flag
                (country: "Tuvalu",
                flag: "tuvalu.png",
                difficulty: 3),
            new Flag
                (country: "Vatican City",
                flag: "vatican_city.png",
                difficulty: 2)
        };
    }
}
